## 7.1 处理缺失值

In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 7.1.1 过滤缺失值

In [2]:
from numpy import nan as NA

In [3]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3]])

In [8]:
cleaned = data.dropna()

In [9]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [10]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [11]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4] = NA

In [13]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -1.046269       NaN       NaN
1  0.964170       NaN       NaN
2 -0.817529       NaN -1.730002
3  0.825300       NaN  0.124398
4 -1.349799 -0.614175  1.223224
5  1.734300  1.112354 -2.030285
6  0.613399 -0.224962 -0.849971

In [18]:
df.dropna()

0         1         2
4 -1.349799 -0.614175  1.223224
5  1.734300  1.112354 -2.030285
6  0.613399 -0.224962 -0.849971

In [19]:
df.dropna(thresh=2)

0         1         2
2 -0.817529       NaN -1.730002
3  0.825300       NaN  0.124398
4 -1.349799 -0.614175  1.223224
5  1.734300  1.112354 -2.030285
6  0.613399 -0.224962 -0.849971

### 7.1.2 补全缺失值

In [20]:
df.fillna(0)

0         1         2
0 -1.046269  0.000000  0.000000
1  0.964170  0.000000  0.000000
2 -0.817529  0.000000 -1.730002
3  0.825300  0.000000  0.124398
4 -1.349799 -0.614175  1.223224
5  1.734300  1.112354 -2.030285
6  0.613399 -0.224962 -0.849971

In [21]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.046269  0.500000  0.000000
1  0.964170  0.500000  0.000000
2 -0.817529  0.500000 -1.730002
3  0.825300  0.500000  0.124398
4 -1.349799 -0.614175  1.223224
5  1.734300  1.112354 -2.030285
6  0.613399 -0.224962 -0.849971

In [23]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -1.046269  0.000000  0.000000
1  0.964170  0.000000  0.000000
2 -0.817529  0.000000 -1.730002
3  0.825300  0.000000  0.124398
4 -1.349799 -0.614175  1.223224
5  1.734300  1.112354 -2.030285
6  0.613399 -0.224962 -0.849971

In [24]:
df = pd.DataFrame(np.random.randn(6, 3))

In [25]:
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.444178 -0.256872 -1.989653
1  1.605792 -1.620195 -0.701206
2 -1.283040       NaN -1.164514
3 -0.600016       NaN -0.759403
4  0.272681       NaN       NaN
5  1.220397       NaN       NaN

In [26]:
df.fillna(method='ffill')

0         1         2
0  0.444178 -0.256872 -1.989653
1  1.605792 -1.620195 -0.701206
2 -1.283040 -1.620195 -1.164514
3 -0.600016 -1.620195 -0.759403
4  0.272681 -1.620195 -0.759403
5  1.220397 -1.620195 -0.759403

In [27]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.444178 -0.256872 -1.989653
1  1.605792 -1.620195 -0.701206
2 -1.283040 -1.620195 -1.164514
3 -0.600016 -1.620195 -0.759403
4  0.272681       NaN -0.759403
5  1.220397       NaN -0.759403

In [28]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 数据转换

### 7.2.1 删除重复值

In [2]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [3]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [4]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [5]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [6]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 7.2.2 使用函数或映射进行数据转换

In [7]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [8]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [9]:
lowercased = data['food'].str.lower()

In [10]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [11]:
data['animal'] = lowercased.map(meat_to_animal)

In [12]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [13]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 7.2.3 替代值

In [14]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [15]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [16]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [17]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [18]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 7.2.4 重命名轴索引

In [19]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [20]:
transform = lambda x: x[:4].upper()

In [21]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [22]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [23]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [24]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [25]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 7.2.5 离散化和分箱

In [2]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [3]:
bins = [18, 25, 35, 60, 100]

In [4]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [5]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [6]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [7]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [8]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [9]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [10]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [11]:
data = np.random.rand(20)

In [12]:
pd.cut(data, 4, precision=2)

[(0.74, 0.98], (0.74, 0.98], (0.74, 0.98], (0.74, 0.98], (0.74, 0.98], ..., (0.74, 0.98], (0.021, 0.26], (0.26, 0.5], (0.5, 0.74], (0.26, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.021, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [13]:
data = np.random.randn(1000)

In [14]:
cats = pd.qcut(data, 4)
cats

[(-0.648, 0.00568], (-0.648, 0.00568], (-0.648, 0.00568], (-2.929, -0.648], (0.00568, 0.693], ..., (0.00568, 0.693], (0.00568, 0.693], (0.00568, 0.693], (0.00568, 0.693], (0.693, 2.522]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.929, -0.648] < (-0.648, 0.00568] < (0.00568, 0.693] < (0.693, 2.522]]

In [15]:
pd.value_counts(cats)

(-2.929, -0.648]     250
(-0.648, 0.00568]    250
(0.00568, 0.693]     250
(0.693, 2.522]       250
Name: count, dtype: int64

In [16]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

[(-1.313, 0.00568], (-1.313, 0.00568], (-1.313, 0.00568], (-1.313, 0.00568], (0.00568, 1.308], ..., (0.00568, 1.308], (0.00568, 1.308], (0.00568, 1.308], (0.00568, 1.308], (0.00568, 1.308]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.929, -1.313] < (-1.313, 0.00568] < (0.00568, 1.308] < (1.308, 2.522]]

### 7.2.6 检测和过滤异常值

In [17]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.019296    -0.014239    -0.009649    -0.038615
std       0.970150     1.008717     0.980676     1.014857
min      -3.363729    -2.977620    -3.473298    -3.070454
25%      -0.679660    -0.700535    -0.649706    -0.741816
50%      -0.060076     0.004032    -0.015647    -0.044461
75%       0.633009     0.664020     0.627161     0.617667
max       2.808761     3.164812     3.280962     3.614088

In [18]:
col = data[2]
col[np.abs(col) > 3]

208    3.280962
641    3.256346
780    3.177529
993   -3.473298
Name: 2, dtype: float64

In [22]:
data[(np.abs(data) > 3).any(axis='columns')]

0         1         2         3
208  1.605701  1.375026  3.280962 -0.944456
387  2.685076  3.164812  0.871821 -0.180332
641 -0.351535 -0.263781  3.256346  0.235137
657  0.356521  2.065147 -1.553284  3.388838
668 -0.317742  0.740604 -0.393560  3.317640
671 -3.363729  1.419886 -1.009407  0.080088
780 -1.115485 -0.338795  3.177529 -0.087198
789  0.485908  0.292892 -2.487500  3.373692
959 -1.078843  0.674874  0.095047 -3.070454
971 -1.565497  0.050131 -0.043668  3.614088
993  0.973934 -0.629490 -3.473298  1.022444

In [23]:
data[data.abs() > 3] = np.sign(data) * 3

In [24]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.018932    -0.014404    -0.009890    -0.040238
std       0.968962     1.008210     0.976823     1.009175
min      -3.000000    -2.977620    -3.000000    -3.000000
25%      -0.679660    -0.700535    -0.649706    -0.741816
50%      -0.060076     0.004032    -0.015647    -0.044461
75%       0.633009     0.664020     0.627161     0.617667
max       2.808761     3.000000     3.000000     3.000000

In [25]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0  1.0
1  1.0 -1.0 -1.0  1.0
2  1.0  1.0 -1.0  1.0
3  1.0 -1.0 -1.0 -1.0
4 -1.0  1.0  1.0  1.0

### 7.2.7 置换和随机抽样

In [26]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [27]:
sampler = np.random.permutation(5)

In [28]:
sampler

array([3, 0, 4, 2, 1])

In [29]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13

In [30]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13

In [31]:
column_sampler = np.random.permutation(7)

In [32]:
column_sampler

array([1, 3, 4, 0, 6, 2, 5])

In [34]:
df.take(column_sampler, axis='columns')

1   3   4   0   6   2   5
0   1   3   4   0   6   2   5
1   8  10  11   7  13   9  12
2  15  17  18  14  20  16  19
3  22  24  25  21  27  23  26
4  29  31  32  28  34  30  33

In [35]:
df.sample(n=3)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27

In [36]:
choices = pd.Series([5, 7, -1, 6, 4])

In [37]:
draws = choices.sample(n=10, replace=True)
draws

3    6
4    4
4    4
3    6
3    6
2   -1
0    5
2   -1
0    5
3    6
dtype: int64

### 7.2.8 计算指标/虚拟变量

In [38]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [40]:
pd.get_dummies(df['key'], dtype=float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [42]:
dummies = pd.get_dummies(df['key'], prefix='key', dtype=float)
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [44]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=mnames, engine='python')
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [45]:
all_genres = []

In [46]:
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [47]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [48]:
dummies = movies['genres'].str.get_dummies('|')
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [49]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [50]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [51]:
np.random.seed(12345)

In [52]:
values = np.random.uniform(size=10)

In [53]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [54]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [55]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

## 7.3 字符串操作

### 7.3.1 字符串对象方法

In [3]:
val = 'a, b,    guido'
val.split(', ')

['a', 'b', '   guido']

In [5]:
pieces = [x.strip() for x in val.split(', ')]
pieces

['a', 'b', 'guido']

In [6]:
'::'.join(pieces)

'a::b::guido'

In [7]:
'guido' in val

True

In [8]:
val.index(', ')

1

In [9]:
val.find(':')

-1

In [10]:
val.index(':')

ValueError: substring not found

In [11]:
val.count(', ')

2

In [12]:
val.replace(', ', '::')

'a::b::   guido'

In [13]:
val.replace(', ', '')

'ab   guido'

### 7.3.2 正则表达式

In [2]:
import re

In [15]:
text = "foo     bar\t baz   \tqux"

In [16]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [17]:
regex = re.compile('\s+')

In [18]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [19]:
regex.findall(text)

['     ', '\t ', '   \t']

In [3]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
# re.IGNORECASE使正则表达式不区分大小写
regex = re.compile(pattern, flags=re.IGNORECASE)

In [4]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [5]:
m = regex.search(text)

In [6]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [7]:
text[m.start():m.end()]

'dave@google.com'

In [8]:
print(regex.match(text))

None


In [9]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [10]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [11]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [12]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [13]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### 7.3.3 pandas中的向量化字符串函数

In [14]:
data = {'Dave': 'dave@google.com',
        'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.con',
        'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.con
Wes                  NaN
dtype: object

In [15]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [16]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [17]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [18]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, con)]
Wes                        NaN
dtype: object

In [25]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [26]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, con)
Wes                      NaN
dtype: object

In [27]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [28]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [29]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  con
Wes      NaN     NaN  NaN

## 7.4 分类数据

In [30]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [31]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [32]:
pd.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [33]:
values = pd.Series([0, 1, 0, 0] * 2)

In [34]:
dim = pd.Series(['apple', 'orange'])

In [35]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [36]:
dim

0     apple
1    orange
dtype: object

In [37]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### 7.4.1 pandas中的分类扩展类型

In [40]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [41]:
N = len(fruits)

In [42]:
rng = np.random.default_rng(seed=12345)

In [43]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [44]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [45]:
c = fruit_cat.array

In [46]:
type(c)

pandas.core.arrays.categorical.Categorical

In [47]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [48]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [49]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [50]:
df['fruit'] = df['fruit'].astype('category')
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [51]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [55]:
categories = ['foo', 'bar', 'baz']

In [53]:
codes = [0, 1, 2, 0, 0, 1]

In [56]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [57]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [58]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

### 7.4.2 分类的计算

In [59]:
rng = np.random.default_rng(seed=12345)

In [60]:
draws = rng.standard_normal(1000)

In [61]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [62]:
bins = pd.qcut(draws, 4)

In [63]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [64]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [65]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [66]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [67]:
bins = pd.Series(bins, name='quartile')

In [68]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())

In [69]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [70]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [71]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [72]:
categories = labels.astype('category')

In [73]:
labels.memory_usage(deep=True)

600000128

In [74]:
categories.memory_usage(deep=True)

10000540

In [75]:
%time _ = labels.astype('category')

CPU times: total: 1.08 s
Wall time: 1.8 s


In [76]:
%timeit labels.value_counts()

806 ms ± 78.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [77]:
%timeit categories.value_counts()

204 ms ± 42.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 7.4.3 分类方法

In [78]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [79]:
cat_s = s.astype('category')

In [80]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [81]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [82]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [83]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [85]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [86]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [87]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [88]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [89]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [90]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [91]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [92]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [93]:
pd.get_dummies(cat_s, dtype=float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0